[aws]
symbol = " "
format = '[$symbol$profile(\($region\))]($style) '

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "
format = '[$symbol$context]($style) '

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "
format ='[$symbol$branch]($style) '

[golang]
symbol = " "
format ='[$symbol$version]($style) '

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}${version}( \($virtualenv\))]($style) '

[ruby]
symbol = " "
format = '[$symbol$version]($style) '

[rust]
symbol = " "

[swift]
symbol = "ﯣ "

