#!/usr/bin/env ruby

git_bundles = [ 
#    "git://github.com/mrtazz/simplenote.vim.git",
#  "git://github.com/astashov/vim-ruby-debugger.git",
#  "git://github.com/msanders/snipmate.vim.git",
    "git://github.com/scrooloose/nerdtree.git",
    "git://github.com/scrooloose/nerdcommenter.git",
#  "git://github.com/timcharper/textile.vim.git",
#  "git://github.com/tpope/vim-cucumber.git",
#  "git://github.com/tpope/vim-fugitive.git",
#  "git://github.com/tpope/vim-git.git",
#  "git://github.com/tpope/vim-haml.git",
#  "git://github.com/tpope/vim-markdown.git",
#  "git://github.com/tpope/vim-rails.git",
#  "git://github.com/tpope/vim-repeat.git",
#  "git://github.com/tpope/vim-surround.git",
#  "git://github.com/tpope/vim-vividchalk.git",
#  "git://github.com/tsaleh/vim-align.git",
#  "git://github.com/tsaleh/vim-shoulda.git",
#  "git://github.com/tsaleh/vim-supertab.git",
#  "git://github.com/tsaleh/vim-tcomment.git",
    "git://github.com/vim-ruby/vim-ruby.git",
    "git://github.com/mileszs/ack.vim.git",
]

vim_org_scripts = [
    ["IndexedSearch", "7062",  "plugin"],
#  ["gist",          "12732", "plugin"],
#  ["jquery",        "12107", "syntax"],
]

require 'fileutils'
require 'open-uri'

cur_dir = File.join(Dir.getwd())
bundles_dir = File.join(File.dirname(__FILE__), "bundle")


git_bundles.each do |url|
    dir = url.split('/').last.sub(/\.git$/, '')
    is_submodule = `grep -c "#{url}" "#{cur_dir}/.gitmodules"`
    if Integer(is_submodule) == 0
        puts "  adding #{url} as submodule..."
        `git submodule add #{url} vim/bundle/#{dir}`
    end
    is_initialized = `grep -c "#{url}" "#{cur_dir}/.git/config"`
    if Integer(is_initialized) == 0
        puts "  initializing #{dir}"
        `git submodule init`
    end
end

puts " Updating submodule bundles via git..."
`git submodule update`

FileUtils.cd(bundles_dir)

vim_org_scripts.each do |name, script_id, script_type|
    puts "  Downloading #{name}"
    local_file = File.join(name, script_type, "#{name}.vim")
    FileUtils.mkdir_p(File.dirname(local_file))
    File.open(local_file, "w") do |file|
        file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
    end
end

#Update help
puts " Updating bundle help tags..."
`vim -e -c "call pathogen#helptags()" -c q`
