#!/usr/bin/env ruby

vim_dir = "vim"

git_bundles = [ 
    "git://github.com/scrooloose/nerdtree.git",
    "git://github.com/scrooloose/nerdcommenter.git",
    "git://github.com/vim-ruby/vim-ruby.git",
    "git://github.com/mileszs/ack.vim.git",
    "git://git.wincent.com/command-t.git",
    "git://github.com/msanders/snipmate.vim.git",
    "git://github.com/chrismetcalf/vim-yankring.git",
]

vim_org_scripts = [
    ["IndexedSearch", "7062",  "plugin"],
]

require 'fileutils'
require 'open-uri'

cur_dir = FileUtils.pwd
bundles_dir = File.join(vim_dir, "bundle")

need_init = false

git_bundles.each do |url|
    dir = url.split('/').last.sub(/\.git$/, '')
    if !system("grep -q \"#{url}\" \"#{cur_dir}/.gitmodules\"")
        puts "  adding #{url} as submodule..."
        `git submodule add #{url} "#{bundles_dir}/#{dir}"`
    end
    if !system("grep -q \"#{url}\" \"#{cur_dir}/.git/config\"")
        need_init = true
    end
end
if need_init
    puts " initializing new submodules"
    `git submodule init`
end

puts " Updating submodule bundles via git..."
`git submodule update`

FileUtils.cd(bundles_dir)

vim_org_scripts.each do |name, script_id, script_type|
    puts "  Downloading #{name}"
    local_file = File.join(name, script_type, "#{name}.vim")
    FileUtils.mkdir_p(File.dirname(local_file))
    File.open(local_file, "w") do |file|
        file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
    end
end

#Update help
puts " Updating bundle help tags..."
`vim -e -c "call pathogen#helptags()" -c q`
