directory: /Volumes/music
library: ~/Documents/beets.blb
import:
  move: yes
  copy: no
  delete: no
  write: yes

  # use auto-tagging where possible
  # do not require confirmation on strong matches
  autotag: yes
  timid: no

  resume: ask
  incremental: no
  none_rec_action: ask
  log:

  quiet: no  # enable with command line option
  quiet_fallback: skip
  default_action: apply

  singletons: no
  languages: []
  detail: no
  flat: no

# use the release-date of the original (first) release of an album?
original_date: yes

# on multi-disk releases, assign track numbers for the whole album.
# If "per disk", make sure tracknames do not collide ("paths" setting).
per_disc_numbering: no

# files matching these patterns are deleted from source after import
clutter: ["Thumbs.DB", ".DS_Store", "*.m3u", ".pls", "*.jpg"]

# files/directories matching one of these patterns are ignored during import
ignore: [".*", "*~", "System Volume Information"]

paths:
  default: %asciify{$albumartist}/%asciify{$album}%aunique{}/$track %asciify{$title}
  singleton: Non-Album/%asciify{$artist}/%asciify{$title}
  comp: Compilations/%asciify{$album}%aunique{}/$track %asciify{$title}

path_sep_replace: _

# filename for the album art
art_filename: cover  # results in "cover.jpg"

max_filename_length: 0  # unlimited

# use mutliple threads during import
threaded: yes
timeout: 5.0
verbose: no

# Auto Tagger ----------------------------------------------------------------

match:
  strong_rec_thresh: 0.1      # match 90% or better for auto import
  medium_rec_thresh: 0.25
  rec_gap_thresh: 0.25
  max_rec:
    missing_tracks: medium
    unmatched_tracks: medium
  distance_weights:
    source: 2.0
    artist: 3.0
    album: 3.0
    media: 1.0
    mediums: 1.0
    year: 1.0
    country: 0.5
    label: 0.5
    catalognum: 0.5
    albumdisambig: 0.5
    album_id: 5.0
    tracks: 2.0
    missing_tracks: 0.9
    unmatched_tracks: 0.6
    track_title: 3.0
    track_artist: 2.0
    track_index: 1.0
    track_length: 2.0
    track_id: 5.0
  preferred:
    countries: []
    media: []
    original_year: no
  ignored: []
  track_length_grace: 10
  track_length_max: 30


# Plugins --------------------------------------------------------------------

plugins: [
  discogs,
  lyrics,
  echonest,
  fetchart,
  embedart,
  lastgenre,
  scrub,
  mbsync,
  mpdupdate,
  #mpdstats,
  missing,
  duplicates
]
pluginpath: []

# Plugins Config -------------------------------------------------------------

lyrics:
  auto: yes
  fallback: ''

echonest_tempo:
  auto: yes

lastgenre:
  # whitelist: ~/.config/beets/genres.txt
  # canoncical: ~/.config/beets/genres-tree.yaml
  fallback: ''
  source: artist

fetchart:
  auto: yes
  maxwidth: 300
  cautious: true
  cover_names: cover folder

embedart:
  auto: yes
  maxwidth: 300

replaygain:
  auto: yes
  overwrite: yes
  albumgain: yes

scrub:
  auto: yes

    # required for mpdstats
  mpd:
    host: localhost
    port: 6600
    password:  # none

  mpdstats:
    rating: False
    # two ratings are calculated:
    # "rolling" based on recent development
    # "stable" based on all-time development
    # rating mix 0.0 is all "rolling", 1.0 is all "stable"
    rating_mix: 0.75

    missing:
      format: $albumartist - $album - $track - $title
    count: no
    total: no

    duplicates:
      checksum: no  # expensive
