directory: /Volumes/music
library: ~/Documents/beets.blb
import:
  write: no
  move: no
  copy: no

# files matching these patterns are deleted from source after import
clutter: ["Thumbs.DB", ".DS_Store", "*.m3u", ".pls", "*.jpg"]

paths:
  default: %asciify{$albumartist}/%asciify{$album}%aunique{}/$track %asciify{$title}
  singleton: Non-Album/%asciify{$artist}/%asciify{$title}
  comp: Compilations/%asciify{$album}%aunique{}/$track %asciify{$title}

# Auto Tagger ----------------------------------------------------------------

match:
  strong_rec_thresh: 0.1      # match 90% or better for auto import
  medium_rec_thresh: 0.25
  rec_gap_thresh: 0.25
  max_rec:
    missing_tracks: medium
    unmatched_tracks: medium
  distance_weights:
    source: 2.0
    artist: 3.0
    album: 3.0
    media: 1.0
    mediums: 1.0
    year: 1.0
    country: 0.5
    label: 0.5
    catalognum: 0.5
    albumdisambig: 0.5
    album_id: 5.0
    tracks: 2.0
    missing_tracks: 0.9
    unmatched_tracks: 0.6
    track_title: 3.0
    track_artist: 2.0
    track_index: 1.0
    track_length: 2.0
    track_id: 5.0
  preferred:
    countries: []
    media: []
    original_year: no
  ignored: []
  track_length_grace: 10
  track_length_max: 30


# Plugins --------------------------------------------------------------------

plugins: [
  discogs,
  echonest,
  lyrics,
  fetchart,
  embedart,
  lastgenre,
  scrub,
  mbsync,
  missing,
  convert,
  duplicates
]
pluginpath: []

# Plugins Config -------------------------------------------------------------

lyrics:
  auto: no
  sources: musixmatch lyricwiki

fetchart:
  auto: no
  cautious: yes
  cover_names: cover folder
  sources: itunes coverart amazon albumart

duplicates:
  checksum: no  # expensive

echonest:
  upload: no

convert:
  format: car
  formats:
    car:
      command: ffmpeg -i $source -y -codec:a libmp3lame -qscale:a 2 $dest
      extension: mp3
      dest: ~/Desktop/carmp3
      max_bitrate: 256
      paths: %asciify{$albumartist} - %asciify{$album}%aunique{}/$track %asciify{$title}

